### ISSUE TITLE
Set `--wp-admin--admin-bar--height: 0;` when admin bar is hidden

### ISSUE THREAD

**Issue by webmandesign** [Swingline0/wpAdminBarHide#5]
First, thank you for this useful extention!

For some time WordPress sets the `--wp-admin--admin-bar--height` CSS property. Please update your extension code and set the `--wp-admin--admin-bar--height` to zero when admin bar is toggled off (WordPress uses `html` as selector for the property setup):
```css
body {
	--wp-admin--admin-bar--height: 0;
}
```

Thank you!
